import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/component/Footer";
import Header from "@/component/Header";
import Carusel from "@/component/Carusel";
import GridF from "@/component/GridF";



const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Mr.Driskell",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="body">
        <Header />
        <Carusel />
        <GridF />
        <Footer />
      </body>
    </html>
  );
}